version: '3'

services:

 nginx:
    image: nginx:1.13
    ports:
      - 8888:80
    volumes:   
      - ./src:/var/www/html
      - ./logs:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php-apache

 php-apache:
    image: php:7.2-apache
    volumes:
      - ./src:/var/www/html
      - ./php-apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
